### ISSUE TITLE
Failure to execute script gui

### ISSUE THREAD

**Issue by CrashyBandicoot0** [pk-hack/CoilSnake#222] opened 2020-06-13 21:45 UTC
When I start up coilsnake, I get this error everytime, I dunno what to do.

**Comment by ShadowOne333** [comment] 2020-06-13 21:46
May I ask, why are you executing script gui instead of the compiled Executable/Binary?

**Comment by CrashyBandicoot0** [comment] 2020-06-13 21:48
I am

**Comment by LittlestCube** [comment] 2020-06-13 21:49
Have you tried simply running `coilsnake` on the command line?

**Comment by ShadowOne333** [comment] 2020-06-13 21:50
What OS system are you on?
Also, the exact error message could help, so try running the executable from terminal/cmd to get the full error message, if running the .exe doesn't bring up any error that is

**Comment by CrashyBandicoot0** [comment] 2020-06-13 21:52
I'm on PC and I actually didn't use the command line

**Comment by CrashyBandicoot0** [comment] 2020-06-13 21:54
Dunno where it is though

**Comment by CrashyBandicoot0** [comment] 2020-06-13 21:58
Where is the Terminal?

**Comment by CrashyBandicoot0** [comment] 2020-06-13 22:06
Nvm about the terminal

**Comment by LittlestCube** [comment] 2020-06-13 22:11
Oh okay. The compiled executable on Windows would then be the .exe, although you can still run it from CMD.

If you're in CMD, you can try dragging the .exe from File Manager onto CMD, and hitting enter. If that doesn't work, try typing the full path of the .exe in manually, or by copy-pasting it (Windows is weird about copying a path though, you have to copy the folder path and then type the name of the .exe).

Let us know how it goes or if you have any questions.

**Comment by CrashyBandicoot0** [comment] 2020-06-14 02:29
Still displays the error

**Comment by ShadowOne333** [comment] 2020-06-15 02:13
What error though?
We cannot do much in terms of help if you don't post the exact error output from either terminal or CoilSnake's pop-up windows.

**Comment by ShadowOne333** [comment] 2021-03-08 18:14
Duplicate of #232, closing.
Also, if you are still having this issue, refer to the last comment on [#232](https://github.com/pk-hack/CoilSnake/issues/232#issuecomment-782977486) , and also to the [General Troubleshooting](https://github.com/pk-hack/CoilSnake#general-troubleshooting) section in the ReadMe, where this issue is addressed.

**Closed by ShadowOne333** 2021-03-08 18:14 UTC
