### ISSUE TITLE
Fatal error detected: Failed to execute script gui

### ISSUE THREAD

**Issue by Krisix13** [pk-hack/CoilSnake#232] opened 2020-11-19 19:33 UTC
i installed coilsnake and python 3.8 but it doesnt work

**Comment by tragicmanner** [comment] 2020-11-19 23:13
I'd recommend giving more details on what didn't work. Did you get any errors? Do you have any screenshots or other examples? Also, since CoilSnake is not so much installed as it is extracted and run, I'm not entirely sure what you mean by installed. Additionally, it does not require python to be installed to run as it is built-in to the executable in Windows, which I'm assuming you are running but it would be good if you gave more details about your operating system and the version you run.

Many of your troubles may be resolved just by checking out: https://github.com/pk-hack/CoilSnake/wiki/Introduction

**Comment by Krisix13** [comment] 2020-11-20 21:26
I use windows 10 and i use coilsnake 4.0
Only version 3.33 works

**Comment by ShadowOne333** [comment] 2020-11-23 00:03
If you use Windows 10, all you should need is just the .EXE.
Unless what you're trying to do is compile it and create an executable .exe out of the source, you don't need Python at all from what I know. Just run the EXE and it should work.

**Comment by tragicmanner** [comment] 2020-11-23 00:15
It would also be helpful if you posted an image of the problem you're having, or even a description of the problem. Saying it doesn't work literally tells us nothing about the specific problem you're seeing. How is it not working?

**Comment by Jovanihere44** [comment] 2020-12-31 21:34
I'm having the same problem #
![Capture](https://user-images.githubusercontent.com/76825524/103426241-fc444c00-4b85-11eb-8831-89efc98790b1.PNG)

**Comment by Jovanihere44** [comment] 2020-12-31 21:34
It just says that

**Comment by ShadowOne333** [comment] 2021-02-21 01:03
is this issue still occurring?
If running the .exe gives the same issue, try running the gui.py file.
Running the .py file requires having Python 3.7 or above installed first.
It should work with this:

`python3 script/gui.py`

**Comment by brentjs0** [comment] 2021-02-22 01:20
@Krisix13 @Jovanihere44 
I just finished debugging this same error message with someone else. It turns out theCoilSnake preferences file was corrupted. Try navigating to your user directory (usually, **C:\Users\_{your user name}_** in Windows) and deleting the file named **.coilsnake.yml**, then opening CoilSnake again.

**Comment by ShadowOne333** [comment] 2021-03-08 18:16
Please, make sure to follow Brent's suggestion to fix the gui issue.
I have also added a section in the ReadMe under "General Troubleshooting", which addresses this problem and mentions Brent's solution.

I'll be closing down this issue in the meanwhile, but I can reopen it if the issue is not solved with Brent's solution.

**Closed by ShadowOne333** 2021-03-08 18:16 UTC
